/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajo_final;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.lang.String;
import javax.swing.BoxLayout;
import javax.swing.JTextField;

/**
 *
 * @author ME
 */
public class DetallesProducto extends javax.swing.JFrame {

    /**
     * Creates new form DetallesProducto
     */
    public DetallesProducto(String nombre, String descripcion, double precio, ImageIcon imagenProducto) {
        initComponents();
        //Panel Principal
        if (imagenProducto != null){
            Image imagen = imagenProducto.getImage().getScaledInstance(1000, 1000, Image.SCALE_SMOOTH);
            Foto_Producto.setIcon(new ImageIcon(imagen));       
        }
        Foto_Producto.setHorizontalAlignment(SwingConstants.CENTER);
        Foto_Producto.setVerticalAlignment(SwingConstants.TOP);
        Foto_Producto.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 10));
        Panel_Principal.add(Foto_Producto, BorderLayout.WEST);
        
        //Panel derecho
        Panel_Derecho.setLayout(new BoxLayout(Panel_Derecho, BoxLayout.Y_AXIS));
        Nombre_Producto = new JLabel(nombre);
        Descripcion_Producto = new JTextField(descripcion);
        Precio_Producto = new JLabel("Precio " + precio + "€");
      
    }

    private DetallesProducto() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Panel_Principal = new javax.swing.JPanel();
        Foto_Producto = new javax.swing.JLabel();
        Volver_Inicio = new javax.swing.JButton();
        Panel_Derecho = new javax.swing.JPanel();
        Nombre_Producto = new javax.swing.JLabel();
        Nombre_Tienda = new javax.swing.JLabel();
        Precio_Producto = new javax.swing.JLabel();
        Descripcion_Producto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 211, 165));

        Panel_Principal.setBackground(new java.awt.Color(229, 211, 165));

        Volver_Inicio.setText("Volver");
        Volver_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_InicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Foto_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Volver_Inicio)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Volver_Inicio)
                .addGap(50, 50, 50)
                .addComponent(Foto_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Derecho.setBackground(new java.awt.Color(229, 211, 165));

        Nombre_Producto.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        Nombre_Producto.setForeground(new java.awt.Color(59, 131, 189));

        Nombre_Tienda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 48)); // NOI18N
        Nombre_Tienda.setForeground(new java.awt.Color(64, 145, 108));
        Nombre_Tienda.setText("Alma Rociera");

        Precio_Producto.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        Precio_Producto.setForeground(new java.awt.Color(138, 149, 151));

        Descripcion_Producto.setText("jTextField1");
        Descripcion_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descripcion_ProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_DerechoLayout = new javax.swing.GroupLayout(Panel_Derecho);
        Panel_Derecho.setLayout(Panel_DerechoLayout);
        Panel_DerechoLayout.setHorizontalGroup(
            Panel_DerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DerechoLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(Nombre_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(Panel_DerechoLayout.createSequentialGroup()
                .addGroup(Panel_DerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DerechoLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(Precio_Producto))
                    .addGroup(Panel_DerechoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(Panel_DerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Descripcion_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_DerechoLayout.setVerticalGroup(
            Panel_DerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DerechoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Nombre_Tienda)
                .addGap(42, 42, 42)
                .addComponent(Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(Descripcion_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Precio_Producto)
                .addContainerGap(609, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_InicioActionPerformed
        Pantalla_Inicio inicio = new Pantalla_Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volver_InicioActionPerformed

    private void Descripcion_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descripcion_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Descripcion_ProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion_Producto;
    private javax.swing.JLabel Foto_Producto;
    private javax.swing.JLabel Nombre_Producto;
    private javax.swing.JLabel Nombre_Tienda;
    private javax.swing.JPanel Panel_Derecho;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JLabel Precio_Producto;
    private javax.swing.JButton Volver_Inicio;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
